-- ccx v0.1 SQLite schema.
-- This file is the source of truth. Migrations in internal/storage are derived
-- from this file. Do not edit this file from inside Phase 1 worktrees — open
-- a contract-amendment PR against main instead.

CREATE TABLE IF NOT EXISTS schema_version (
    version INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS profiles (
    name           TEXT PRIMARY KEY,
    config_dir     TEXT UNIQUE NOT NULL,
    label          TEXT,
    color          TEXT,
    created_at     INTEGER NOT NULL,
    last_used_at   INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    profile_name        TEXT NOT NULL,
    session_id          TEXT NOT NULL,
    event_uuid          TEXT NOT NULL,
    ts                  INTEGER NOT NULL,
    project             TEXT,
    model               TEXT,
    input_tokens        INTEGER NOT NULL DEFAULT 0,
    output_tokens       INTEGER NOT NULL DEFAULT 0,
    cache_read_tokens   INTEGER NOT NULL DEFAULT 0,
    cache_create_tokens INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (profile_name, event_uuid),
    FOREIGN KEY (profile_name) REFERENCES profiles(name) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS events_profile_ts ON events(profile_name, ts);
CREATE INDEX IF NOT EXISTS events_project    ON events(project);

CREATE TABLE IF NOT EXISTS scan_cursors (
    profile_name TEXT NOT NULL,
    file_path    TEXT NOT NULL,
    offset       INTEGER NOT NULL DEFAULT 0,
    inode        INTEGER,
    PRIMARY KEY (profile_name, file_path),
    FOREIGN KEY (profile_name) REFERENCES profiles(name) ON DELETE CASCADE
);

-- Seed the schema version
INSERT OR IGNORE INTO schema_version (version) VALUES (1);
